#!/usr/bin/env node

const { spawn } = require('child_process');

const cmd = process.argv[2];
const args = process.argv.slice(3);

const child = spawn(cmd, args);

child.on('exit', () => {
  process.exit();
});

child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);

process.stdin.on('data', () => {});
process.stdin.once('close', () => {
    child.kill('SIGTERM');
});